# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'intersections.ui'
#
# Created by: PyQt4 UI code generator 4.12.1
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_Intersections(object):
    def setupUi(self, Intersections):
        Intersections.setObjectName(_fromUtf8("Intersections"))
        Intersections.resize(740, 858)
        self.layoutWidget = QtGui.QWidget(Intersections)
        self.layoutWidget.setGeometry(QtCore.QRect(10, 10, 721, 846))
        self.layoutWidget.setObjectName(_fromUtf8("layoutWidget"))
        self.gridLayout = QtGui.QGridLayout(self.layoutWidget)
        self.gridLayout.setMargin(0)
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.n12 = QtGui.QLineEdit(self.layoutWidget)
        self.n12.setObjectName(_fromUtf8("n12"))
        self.gridLayout.addWidget(self.n12, 4, 0, 1, 1)
        self.n22 = QtGui.QLineEdit(self.layoutWidget)
        self.n22.setObjectName(_fromUtf8("n22"))
        self.gridLayout.addWidget(self.n22, 4, 1, 1, 1)
        self.label_6 = QtGui.QLabel(self.layoutWidget)
        self.label_6.setObjectName(_fromUtf8("label_6"))
        self.gridLayout.addWidget(self.label_6, 9, 0, 3, 1)
        self.label_3 = QtGui.QLabel(self.layoutWidget)
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.gridLayout.addWidget(self.label_3, 1, 1, 1, 1)
        self.c1 = QtGui.QLineEdit(self.layoutWidget)
        self.c1.setObjectName(_fromUtf8("c1"))
        self.gridLayout.addWidget(self.c1, 23, 1, 1, 1)
        self.angle_proj = QtGui.QLineEdit(self.layoutWidget)
        self.angle_proj.setObjectName(_fromUtf8("angle_proj"))
        self.gridLayout.addWidget(self.angle_proj, 12, 1, 1, 1)
        self.label_4 = QtGui.QLabel(self.layoutWidget)
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.gridLayout.addWidget(self.label_4, 0, 0, 1, 1)
        self.n21 = QtGui.QLineEdit(self.layoutWidget)
        self.n21.setObjectName(_fromUtf8("n21"))
        self.gridLayout.addWidget(self.n21, 3, 1, 1, 1)
        self.n_proj1 = QtGui.QLineEdit(self.layoutWidget)
        self.n_proj1.setObjectName(_fromUtf8("n_proj1"))
        self.gridLayout.addWidget(self.n_proj1, 10, 1, 1, 1)
        self.n10 = QtGui.QLineEdit(self.layoutWidget)
        self.n10.setObjectName(_fromUtf8("n10"))
        self.gridLayout.addWidget(self.n10, 2, 0, 1, 1)
        self.label_10 = QtGui.QLabel(self.layoutWidget)
        self.label_10.setObjectName(_fromUtf8("label_10"))
        self.gridLayout.addWidget(self.label_10, 25, 0, 1, 1)
        self.label_5 = QtGui.QLabel(self.layoutWidget)
        self.label_5.setObjectName(_fromUtf8("label_5"))
        self.gridLayout.addWidget(self.label_5, 8, 0, 1, 2)
        self.label = QtGui.QLabel(self.layoutWidget)
        self.label.setObjectName(_fromUtf8("label"))
        self.gridLayout.addWidget(self.label, 12, 0, 1, 1)
        self.n_proj2 = QtGui.QLineEdit(self.layoutWidget)
        self.n_proj2.setObjectName(_fromUtf8("n_proj2"))
        self.gridLayout.addWidget(self.n_proj2, 11, 1, 1, 1)
        self.pushButton_copy2 = QtGui.QPushButton(self.layoutWidget)
        self.pushButton_copy2.setObjectName(_fromUtf8("pushButton_copy2"))
        self.gridLayout.addWidget(self.pushButton_copy2, 16, 1, 1, 1)
        self.label_2 = QtGui.QLabel(self.layoutWidget)
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.gridLayout.addWidget(self.label_2, 1, 0, 1, 1)
        self.n_proj0 = QtGui.QLineEdit(self.layoutWidget)
        self.n_proj0.setObjectName(_fromUtf8("n_proj0"))
        self.gridLayout.addWidget(self.n_proj0, 9, 1, 1, 1)
        self.label_7 = QtGui.QLabel(self.layoutWidget)
        self.label_7.setObjectName(_fromUtf8("label_7"))
        self.gridLayout.addWidget(self.label_7, 18, 0, 1, 1)
        self.n11 = QtGui.QLineEdit(self.layoutWidget)
        self.n11.setObjectName(_fromUtf8("n11"))
        self.gridLayout.addWidget(self.n11, 3, 0, 1, 1)
        self.c_angle = QtGui.QLineEdit(self.layoutWidget)
        self.c_angle.setObjectName(_fromUtf8("c_angle"))
        self.gridLayout.addWidget(self.c_angle, 25, 1, 1, 1)
        self.n20 = QtGui.QLineEdit(self.layoutWidget)
        self.n20.setObjectName(_fromUtf8("n20"))
        self.gridLayout.addWidget(self.n20, 2, 1, 1, 1)
        self.pushButton_intersections_plans = QtGui.QPushButton(self.layoutWidget)
        self.pushButton_intersections_plans.setObjectName(_fromUtf8("pushButton_intersections_plans"))
        self.gridLayout.addWidget(self.pushButton_intersections_plans, 5, 0, 1, 1)
        self.pushButton_intersection_proj = QtGui.QPushButton(self.layoutWidget)
        self.pushButton_intersection_proj.setObjectName(_fromUtf8("pushButton_intersection_proj"))
        self.gridLayout.addWidget(self.pushButton_intersection_proj, 15, 0, 1, 1)
        self.pushButton_intersection_cone = QtGui.QPushButton(self.layoutWidget)
        self.pushButton_intersection_cone.setObjectName(_fromUtf8("pushButton_intersection_cone"))
        self.gridLayout.addWidget(self.pushButton_intersection_cone, 26, 0, 1, 1)
        self.checkBox = QtGui.QCheckBox(self.layoutWidget)
        self.checkBox.setObjectName(_fromUtf8("checkBox"))
        self.gridLayout.addWidget(self.checkBox, 5, 1, 1, 1)
        self.checkBox_3 = QtGui.QCheckBox(self.layoutWidget)
        self.checkBox_3.setObjectName(_fromUtf8("checkBox_3"))
        self.gridLayout.addWidget(self.checkBox_3, 26, 1, 1, 1)
        self.intersection_planes = QtGui.QLineEdit(self.layoutWidget)
        self.intersection_planes.setObjectName(_fromUtf8("intersection_planes"))
        self.gridLayout.addWidget(self.intersection_planes, 6, 0, 1, 1)
        self.pushButton_copy = QtGui.QPushButton(self.layoutWidget)
        self.pushButton_copy.setObjectName(_fromUtf8("pushButton_copy"))
        self.gridLayout.addWidget(self.pushButton_copy, 6, 1, 1, 1)
        self.intersection_dir_proj = QtGui.QLineEdit(self.layoutWidget)
        self.intersection_dir_proj.setObjectName(_fromUtf8("intersection_dir_proj"))
        self.gridLayout.addWidget(self.intersection_dir_proj, 16, 0, 1, 1)
        self.intersection_cone = QtGui.QLineEdit(self.layoutWidget)
        self.intersection_cone.setObjectName(_fromUtf8("intersection_cone"))
        self.gridLayout.addWidget(self.intersection_cone, 27, 0, 1, 1)
        self.pushButton_copy3 = QtGui.QPushButton(self.layoutWidget)
        self.pushButton_copy3.setObjectName(_fromUtf8("pushButton_copy3"))
        self.gridLayout.addWidget(self.pushButton_copy3, 27, 1, 1, 1)
        self.checkBox_2 = QtGui.QCheckBox(self.layoutWidget)
        self.checkBox_2.setObjectName(_fromUtf8("checkBox_2"))
        self.gridLayout.addWidget(self.checkBox_2, 15, 1, 1, 1)
        self.intersection_cone2 = QtGui.QLineEdit(self.layoutWidget)
        self.intersection_cone2.setObjectName(_fromUtf8("intersection_cone2"))
        self.gridLayout.addWidget(self.intersection_cone2, 28, 0, 1, 1)
        self.n1 = QtGui.QLineEdit(self.layoutWidget)
        self.n1.setObjectName(_fromUtf8("n1"))
        self.gridLayout.addWidget(self.n1, 20, 1, 1, 1)
        self.label_9 = QtGui.QLabel(self.layoutWidget)
        self.label_9.setObjectName(_fromUtf8("label_9"))
        self.gridLayout.addWidget(self.label_9, 22, 0, 3, 1)
        self.pushButton_copy4 = QtGui.QPushButton(self.layoutWidget)
        self.pushButton_copy4.setObjectName(_fromUtf8("pushButton_copy4"))
        self.gridLayout.addWidget(self.pushButton_copy4, 28, 1, 1, 1)
        self.c2 = QtGui.QLineEdit(self.layoutWidget)
        self.c2.setObjectName(_fromUtf8("c2"))
        self.gridLayout.addWidget(self.c2, 24, 1, 1, 1)
        self.c0 = QtGui.QLineEdit(self.layoutWidget)
        self.c0.setObjectName(_fromUtf8("c0"))
        self.gridLayout.addWidget(self.c0, 22, 1, 1, 1)
        self.n2 = QtGui.QLineEdit(self.layoutWidget)
        self.n2.setObjectName(_fromUtf8("n2"))
        self.gridLayout.addWidget(self.n2, 21, 1, 1, 1)
        self.n0 = QtGui.QLineEdit(self.layoutWidget)
        self.n0.setObjectName(_fromUtf8("n0"))
        self.gridLayout.addWidget(self.n0, 19, 1, 1, 1)
        self.label_8 = QtGui.QLabel(self.layoutWidget)
        self.label_8.setObjectName(_fromUtf8("label_8"))
        self.gridLayout.addWidget(self.label_8, 19, 0, 3, 1)

        self.retranslateUi(Intersections)
        QtCore.QMetaObject.connectSlotsByName(Intersections)
        Intersections.setTabOrder(self.n10, self.n11)
        Intersections.setTabOrder(self.n11, self.n12)
        Intersections.setTabOrder(self.n12, self.n20)
        Intersections.setTabOrder(self.n20, self.n21)
        Intersections.setTabOrder(self.n21, self.n22)
        Intersections.setTabOrder(self.n22, self.pushButton_intersections_plans)
        Intersections.setTabOrder(self.pushButton_intersections_plans, self.checkBox)
        Intersections.setTabOrder(self.checkBox, self.intersection_planes)
        Intersections.setTabOrder(self.intersection_planes, self.n_proj0)
        Intersections.setTabOrder(self.n_proj0, self.n_proj1)
        Intersections.setTabOrder(self.n_proj1, self.n_proj2)
        Intersections.setTabOrder(self.n_proj2, self.angle_proj)
        Intersections.setTabOrder(self.angle_proj, self.pushButton_intersection_proj)
        Intersections.setTabOrder(self.pushButton_intersection_proj, self.checkBox_2)
        Intersections.setTabOrder(self.checkBox_2, self.intersection_dir_proj)
        Intersections.setTabOrder(self.intersection_dir_proj, self.n0)
        Intersections.setTabOrder(self.n0, self.n1)
        Intersections.setTabOrder(self.n1, self.n2)
        Intersections.setTabOrder(self.n2, self.c0)
        Intersections.setTabOrder(self.c0, self.c1)
        Intersections.setTabOrder(self.c1, self.c2)
        Intersections.setTabOrder(self.c2, self.c_angle)
        Intersections.setTabOrder(self.c_angle, self.pushButton_intersection_cone)
        Intersections.setTabOrder(self.pushButton_intersection_cone, self.checkBox_3)
        Intersections.setTabOrder(self.checkBox_3, self.intersection_cone)

    def retranslateUi(self, Intersections):
        Intersections.setWindowTitle(_translate("Intersections", "Intersections", None))
        self.label_6.setText(_translate("Intersections", "n", None))
        self.label_3.setText(_translate("Intersections", "n2", None))
        self.label_4.setText(_translate("Intersections", "Intersection plane n1 and n2", None))
        self.label_10.setText(_translate("Intersections", "inclination angle", None))
        self.label_5.setText(_translate("Intersections", "Intersection projected direction, plane n", None))
        self.label.setText(_translate("Intersections", "angle", None))
        self.pushButton_copy2.setText(_translate("Intersections", "Copy to pole", None))
        self.label_2.setText(_translate("Intersections", "n1", None))
        self.label_7.setText(_translate("Intersections", "Intersection plane n, cone c", None))
        self.pushButton_intersections_plans.setText(_translate("Intersections", "OK", None))
        self.pushButton_intersection_proj.setText(_translate("Intersections", "OK", None))
        self.pushButton_intersection_cone.setText(_translate("Intersections", "OK", None))
        self.checkBox.setText(_translate("Intersections", "directions", None))
        self.checkBox_3.setText(_translate("Intersections", "directions", None))
        self.pushButton_copy.setText(_translate("Intersections", "Copy to pole", None))
        self.pushButton_copy3.setText(_translate("Intersections", "Copy to pole", None))
        self.checkBox_2.setText(_translate("Intersections", "directions", None))
        self.label_9.setText(_translate("Intersections", "c", None))
        self.pushButton_copy4.setText(_translate("Intersections", "Copy to pole", None))
        self.label_8.setText(_translate("Intersections", "n", None))

