# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'intersections.ui'
#
# Created by: PyQt4 UI code generator 4.12.1
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_Intersections(object):
    def setupUi(self, Intersections):
        Intersections.setObjectName(_fromUtf8("Intersections"))
        Intersections.resize(734, 838)
        self.layoutWidget = QtGui.QWidget(Intersections)
        self.layoutWidget.setGeometry(QtCore.QRect(10, 10, 721, 822))
        self.layoutWidget.setObjectName(_fromUtf8("layoutWidget"))
        self.gridLayout = QtGui.QGridLayout(self.layoutWidget)
        self.gridLayout.setMargin(0)
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.n12 = QtGui.QLineEdit(self.layoutWidget)
        self.n12.setObjectName(_fromUtf8("n12"))
        self.gridLayout.addWidget(self.n12, 4, 0, 1, 1)
        self.n22 = QtGui.QLineEdit(self.layoutWidget)
        self.n22.setObjectName(_fromUtf8("n22"))
        self.gridLayout.addWidget(self.n22, 4, 1, 1, 1)
        self.pushButton = QtGui.QPushButton(self.layoutWidget)
        self.pushButton.setObjectName(_fromUtf8("pushButton"))
        self.gridLayout.addWidget(self.pushButton, 5, 0, 1, 2)
        self.label_6 = QtGui.QLabel(self.layoutWidget)
        self.label_6.setObjectName(_fromUtf8("label_6"))
        self.gridLayout.addWidget(self.label_6, 9, 0, 3, 1)
        self.label_3 = QtGui.QLabel(self.layoutWidget)
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.gridLayout.addWidget(self.label_3, 1, 1, 1, 1)
        self.lineEdit = QtGui.QLineEdit(self.layoutWidget)
        self.lineEdit.setObjectName(_fromUtf8("lineEdit"))
        self.gridLayout.addWidget(self.lineEdit, 12, 1, 1, 1)
        self.intersection_planes = QtGui.QLineEdit(self.layoutWidget)
        self.intersection_planes.setObjectName(_fromUtf8("intersection_planes"))
        self.gridLayout.addWidget(self.intersection_planes, 6, 0, 1, 2)
        self.label_4 = QtGui.QLabel(self.layoutWidget)
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.gridLayout.addWidget(self.label_4, 0, 0, 1, 1)
        self.n21 = QtGui.QLineEdit(self.layoutWidget)
        self.n21.setObjectName(_fromUtf8("n21"))
        self.gridLayout.addWidget(self.n21, 3, 1, 1, 1)
        self.lineEdit_3 = QtGui.QLineEdit(self.layoutWidget)
        self.lineEdit_3.setObjectName(_fromUtf8("lineEdit_3"))
        self.gridLayout.addWidget(self.lineEdit_3, 10, 1, 1, 1)
        self.n10 = QtGui.QLineEdit(self.layoutWidget)
        self.n10.setObjectName(_fromUtf8("n10"))
        self.gridLayout.addWidget(self.n10, 2, 0, 1, 1)
        self.lineEdit_12 = QtGui.QLineEdit(self.layoutWidget)
        self.lineEdit_12.setObjectName(_fromUtf8("lineEdit_12"))
        self.gridLayout.addWidget(self.lineEdit_12, 24, 1, 1, 1)
        self.label_10 = QtGui.QLabel(self.layoutWidget)
        self.label_10.setObjectName(_fromUtf8("label_10"))
        self.gridLayout.addWidget(self.label_10, 25, 0, 1, 1)
        self.lineEdit_13 = QtGui.QLineEdit(self.layoutWidget)
        self.lineEdit_13.setObjectName(_fromUtf8("lineEdit_13"))
        self.gridLayout.addWidget(self.lineEdit_13, 27, 0, 1, 2)
        self.label_5 = QtGui.QLabel(self.layoutWidget)
        self.label_5.setObjectName(_fromUtf8("label_5"))
        self.gridLayout.addWidget(self.label_5, 8, 0, 1, 2)
        self.label = QtGui.QLabel(self.layoutWidget)
        self.label.setObjectName(_fromUtf8("label"))
        self.gridLayout.addWidget(self.label, 12, 0, 1, 1)
        self.lineEdit_2 = QtGui.QLineEdit(self.layoutWidget)
        self.lineEdit_2.setObjectName(_fromUtf8("lineEdit_2"))
        self.gridLayout.addWidget(self.lineEdit_2, 11, 1, 1, 1)
        self.label_2 = QtGui.QLabel(self.layoutWidget)
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.gridLayout.addWidget(self.label_2, 1, 0, 1, 1)
        self.lineEdit_4 = QtGui.QLineEdit(self.layoutWidget)
        self.lineEdit_4.setObjectName(_fromUtf8("lineEdit_4"))
        self.gridLayout.addWidget(self.lineEdit_4, 9, 1, 1, 1)
        self.label_9 = QtGui.QLabel(self.layoutWidget)
        self.label_9.setObjectName(_fromUtf8("label_9"))
        self.gridLayout.addWidget(self.label_9, 22, 0, 1, 1)
        self.lineEdit_7 = QtGui.QLineEdit(self.layoutWidget)
        self.lineEdit_7.setObjectName(_fromUtf8("lineEdit_7"))
        self.gridLayout.addWidget(self.lineEdit_7, 20, 1, 1, 1)
        self.lineEdit_5 = QtGui.QLineEdit(self.layoutWidget)
        self.lineEdit_5.setObjectName(_fromUtf8("lineEdit_5"))
        self.gridLayout.addWidget(self.lineEdit_5, 16, 0, 1, 2)
        self.label_7 = QtGui.QLabel(self.layoutWidget)
        self.label_7.setObjectName(_fromUtf8("label_7"))
        self.gridLayout.addWidget(self.label_7, 18, 0, 1, 1)
        self.n11 = QtGui.QLineEdit(self.layoutWidget)
        self.n11.setObjectName(_fromUtf8("n11"))
        self.gridLayout.addWidget(self.n11, 3, 0, 1, 1)
        self.label_8 = QtGui.QLabel(self.layoutWidget)
        self.label_8.setObjectName(_fromUtf8("label_8"))
        self.gridLayout.addWidget(self.label_8, 19, 0, 3, 1)
        self.lineEdit_9 = QtGui.QLineEdit(self.layoutWidget)
        self.lineEdit_9.setObjectName(_fromUtf8("lineEdit_9"))
        self.gridLayout.addWidget(self.lineEdit_9, 22, 1, 1, 1)
        self.lineEdit_6 = QtGui.QLineEdit(self.layoutWidget)
        self.lineEdit_6.setObjectName(_fromUtf8("lineEdit_6"))
        self.gridLayout.addWidget(self.lineEdit_6, 19, 1, 1, 1)
        self.pushButton_2 = QtGui.QPushButton(self.layoutWidget)
        self.pushButton_2.setObjectName(_fromUtf8("pushButton_2"))
        self.gridLayout.addWidget(self.pushButton_2, 15, 0, 1, 2)
        self.lineEdit_8 = QtGui.QLineEdit(self.layoutWidget)
        self.lineEdit_8.setObjectName(_fromUtf8("lineEdit_8"))
        self.gridLayout.addWidget(self.lineEdit_8, 21, 1, 1, 1)
        self.lineEdit_10 = QtGui.QLineEdit(self.layoutWidget)
        self.lineEdit_10.setObjectName(_fromUtf8("lineEdit_10"))
        self.gridLayout.addWidget(self.lineEdit_10, 23, 1, 1, 1)
        self.lineEdit_11 = QtGui.QLineEdit(self.layoutWidget)
        self.lineEdit_11.setObjectName(_fromUtf8("lineEdit_11"))
        self.gridLayout.addWidget(self.lineEdit_11, 25, 1, 1, 1)
        self.n20 = QtGui.QLineEdit(self.layoutWidget)
        self.n20.setObjectName(_fromUtf8("n20"))
        self.gridLayout.addWidget(self.n20, 2, 1, 1, 1)
        self.pushButton_3 = QtGui.QPushButton(self.layoutWidget)
        self.pushButton_3.setObjectName(_fromUtf8("pushButton_3"))
        self.gridLayout.addWidget(self.pushButton_3, 26, 0, 1, 2)

        self.retranslateUi(Intersections)
        QtCore.QMetaObject.connectSlotsByName(Intersections)
        Intersections.setTabOrder(self.n10, self.n11)
        Intersections.setTabOrder(self.n11, self.n12)
        Intersections.setTabOrder(self.n12, self.n20)
        Intersections.setTabOrder(self.n20, self.n21)
        Intersections.setTabOrder(self.n21, self.n22)

    def retranslateUi(self, Intersections):
        Intersections.setWindowTitle(_translate("Intersections", "Intersections", None))
        self.pushButton.setText(_translate("Intersections", "OK", None))
        self.label_6.setText(_translate("Intersections", "n", None))
        self.label_3.setText(_translate("Intersections", "d2", None))
        self.label_4.setText(_translate("Intersections", "Intersection plane n1 and n2", None))
        self.label_10.setText(_translate("Intersections", "inclination angle", None))
        self.label_5.setText(_translate("Intersections", "Intersection projected direction, plane n", None))
        self.label.setText(_translate("Intersections", "angle", None))
        self.label_2.setText(_translate("Intersections", "n1", None))
        self.label_9.setText(_translate("Intersections", "c", None))
        self.label_7.setText(_translate("Intersections", "Intersection plane n -cone c", None))
        self.label_8.setText(_translate("Intersections", "n", None))
        self.pushButton_2.setText(_translate("Intersections", "OK", None))
        self.pushButton_3.setText(_translate("Intersections", "OK", None))

