# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'stereo-pyqt.ui'
#
# Created by: PyQt4 UI code generator 4.12.1
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_StereoProj(object):
    def setupUi(self, StereoProj):
        StereoProj.setObjectName(_fromUtf8("StereoProj"))
        StereoProj.resize(1152, 867)
        self.centralwidget = QtGui.QWidget(StereoProj)
        self.centralwidget.setObjectName(_fromUtf8("centralwidget"))
        self.gridLayout_7 = QtGui.QGridLayout(self.centralwidget)
        self.gridLayout_7.setObjectName(_fromUtf8("gridLayout_7"))
        self.gridLayout = QtGui.QGridLayout()
        self.gridLayout.setSizeConstraint(QtGui.QLayout.SetDefaultConstraint)
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.groupBox_5 = QtGui.QGroupBox(self.centralwidget)
        self.groupBox_5.setMaximumSize(QtCore.QSize(150, 16777215))
        self.groupBox_5.setObjectName(_fromUtf8("groupBox_5"))
        self.gridLayout_6 = QtGui.QGridLayout(self.groupBox_5)
        self.gridLayout_6.setObjectName(_fromUtf8("gridLayout_6"))
        self.lab_coord = QtGui.QLabel(self.groupBox_5)
        self.lab_coord.setObjectName(_fromUtf8("lab_coord"))
        self.gridLayout_6.addWidget(self.lab_coord, 5, 0, 1, 3)
        self.phi1_entry = QtGui.QLineEdit(self.groupBox_5)
        self.phi1_entry.setObjectName(_fromUtf8("phi1_entry"))
        self.gridLayout_6.addWidget(self.phi1_entry, 0, 0, 1, 1)
        self.coord_label = QtGui.QLabel(self.groupBox_5)
        self.coord_label.setText(_fromUtf8(""))
        self.coord_label.setObjectName(_fromUtf8("coord_label"))
        self.gridLayout_6.addWidget(self.coord_label, 6, 0, 1, 2)
        self.phi_entry = QtGui.QLineEdit(self.groupBox_5)
        self.phi_entry.setObjectName(_fromUtf8("phi_entry"))
        self.gridLayout_6.addWidget(self.phi_entry, 0, 1, 1, 1)
        self.button_trace2 = QtGui.QPushButton(self.groupBox_5)
        self.button_trace2.setObjectName(_fromUtf8("button_trace2"))
        self.gridLayout_6.addWidget(self.button_trace2, 1, 0, 1, 2)
        self.angle_euler_label = QtGui.QLabel(self.groupBox_5)
        self.angle_euler_label.setText(_fromUtf8(""))
        self.angle_euler_label.setObjectName(_fromUtf8("angle_euler_label"))
        self.gridLayout_6.addWidget(self.angle_euler_label, 3, 0, 1, 3)
        self.phi2_entry = QtGui.QLineEdit(self.groupBox_5)
        self.phi2_entry.setObjectName(_fromUtf8("phi2_entry"))
        self.gridLayout_6.addWidget(self.phi2_entry, 0, 2, 1, 1)
        self.lab_euler2 = QtGui.QLabel(self.groupBox_5)
        self.lab_euler2.setObjectName(_fromUtf8("lab_euler2"))
        self.gridLayout_6.addWidget(self.lab_euler2, 2, 0, 1, 3)
        self.pushButton_copy_to_euler = QtGui.QPushButton(self.groupBox_5)
        self.pushButton_copy_to_euler.setObjectName(_fromUtf8("pushButton_copy_to_euler"))
        self.gridLayout_6.addWidget(self.pushButton_copy_to_euler, 4, 0, 1, 3)
        self.gridLayout.addWidget(self.groupBox_5, 3, 3, 1, 1)
        self.groupBox_4 = QtGui.QGroupBox(self.centralwidget)
        self.groupBox_4.setMaximumSize(QtCore.QSize(150, 16777215))
        self.groupBox_4.setObjectName(_fromUtf8("groupBox_4"))
        self.gridLayout_5 = QtGui.QGridLayout(self.groupBox_4)
        self.gridLayout_5.setObjectName(_fromUtf8("gridLayout_5"))
        self.undo_trace_schmid = QtGui.QPushButton(self.groupBox_4)
        self.undo_trace_schmid.setObjectName(_fromUtf8("undo_trace_schmid"))
        self.gridLayout_5.addWidget(self.undo_trace_schmid, 5, 3, 1, 1)
        self.norm_button = QtGui.QPushButton(self.groupBox_4)
        self.norm_button.setObjectName(_fromUtf8("norm_button"))
        self.gridLayout_5.addWidget(self.norm_button, 7, 0, 1, 1)
        self.undo_sym_button = QtGui.QPushButton(self.groupBox_4)
        self.undo_sym_button.setObjectName(_fromUtf8("undo_sym_button"))
        self.gridLayout_5.addWidget(self.undo_sym_button, 2, 3, 1, 1)
        self.trace_schmid_button = QtGui.QPushButton(self.groupBox_4)
        self.trace_schmid_button.setObjectName(_fromUtf8("trace_schmid_button"))
        self.gridLayout_5.addWidget(self.trace_schmid_button, 5, 0, 1, 3)
        self.addpole_button = QtGui.QPushButton(self.groupBox_4)
        self.addpole_button.setObjectName(_fromUtf8("addpole_button"))
        self.gridLayout_5.addWidget(self.addpole_button, 1, 0, 1, 3)
        self.dhkl_label = QtGui.QLabel(self.groupBox_4)
        self.dhkl_label.setText(_fromUtf8(""))
        self.dhkl_label.setObjectName(_fromUtf8("dhkl_label"))
        self.gridLayout_5.addWidget(self.dhkl_label, 7, 2, 1, 2)
        self.trace_plan_button = QtGui.QPushButton(self.groupBox_4)
        self.trace_plan_button.setObjectName(_fromUtf8("trace_plan_button"))
        self.gridLayout_5.addWidget(self.trace_plan_button, 3, 0, 1, 3)
        self.pole3_entry = QtGui.QLineEdit(self.groupBox_4)
        self.pole3_entry.setObjectName(_fromUtf8("pole3_entry"))
        self.gridLayout_5.addWidget(self.pole3_entry, 0, 3, 1, 1)
        self.undo_trace_plan_sym_button = QtGui.QPushButton(self.groupBox_4)
        self.undo_trace_plan_sym_button.setObjectName(_fromUtf8("undo_trace_plan_sym_button"))
        self.gridLayout_5.addWidget(self.undo_trace_plan_sym_button, 4, 3, 1, 1)
        self.trace_plan_sym_button = QtGui.QPushButton(self.groupBox_4)
        self.trace_plan_sym_button.setObjectName(_fromUtf8("trace_plan_sym_button"))
        self.gridLayout_5.addWidget(self.trace_plan_sym_button, 4, 0, 1, 3)
        self.sym_button = QtGui.QPushButton(self.groupBox_4)
        self.sym_button.setObjectName(_fromUtf8("sym_button"))
        self.gridLayout_5.addWidget(self.sym_button, 2, 0, 1, 3)
        self.undo_trace_plan_button = QtGui.QPushButton(self.groupBox_4)
        self.undo_trace_plan_button.setObjectName(_fromUtf8("undo_trace_plan_button"))
        self.gridLayout_5.addWidget(self.undo_trace_plan_button, 3, 3, 1, 1)
        self.undo_addpole_button = QtGui.QPushButton(self.groupBox_4)
        self.undo_addpole_button.setObjectName(_fromUtf8("undo_addpole_button"))
        self.gridLayout_5.addWidget(self.undo_addpole_button, 1, 3, 1, 1)
        self.pole2_entry = QtGui.QLineEdit(self.groupBox_4)
        self.pole2_entry.setObjectName(_fromUtf8("pole2_entry"))
        self.gridLayout_5.addWidget(self.pole2_entry, 0, 2, 1, 1)
        self.pole1_entry = QtGui.QLineEdit(self.groupBox_4)
        self.pole1_entry.setObjectName(_fromUtf8("pole1_entry"))
        self.gridLayout_5.addWidget(self.pole1_entry, 0, 0, 1, 1)
        self.undo_trace_cone_button = QtGui.QPushButton(self.groupBox_4)
        self.undo_trace_cone_button.setObjectName(_fromUtf8("undo_trace_cone_button"))
        self.gridLayout_5.addWidget(self.undo_trace_cone_button, 6, 3, 1, 1)
        self.inclination_entry = QtGui.QLineEdit(self.groupBox_4)
        self.inclination_entry.setObjectName(_fromUtf8("inclination_entry"))
        self.gridLayout_5.addWidget(self.inclination_entry, 6, 2, 1, 1)
        self.trace_cone_button = QtGui.QPushButton(self.groupBox_4)
        self.trace_cone_button.setObjectName(_fromUtf8("trace_cone_button"))
        self.gridLayout_5.addWidget(self.trace_cone_button, 6, 0, 1, 2)
        self.gridLayout.addWidget(self.groupBox_4, 2, 3, 1, 1)
        self.groupBox_2 = QtGui.QGroupBox(self.centralwidget)
        self.groupBox_2.setEnabled(True)
        self.groupBox_2.setMaximumSize(QtCore.QSize(150, 16777215))
        self.groupBox_2.setObjectName(_fromUtf8("groupBox_2"))
        self.gridLayout_3 = QtGui.QGridLayout(self.groupBox_2)
        self.gridLayout_3.setMargin(5)
        self.gridLayout_3.setSpacing(5)
        self.gridLayout_3.setObjectName(_fromUtf8("gridLayout_3"))
        self.diff_label = QtGui.QLabel(self.groupBox_2)
        self.diff_label.setObjectName(_fromUtf8("diff_label"))
        self.gridLayout_3.addWidget(self.diff_label, 0, 0, 1, 3)
        self.hexa_button = QtGui.QCheckBox(self.groupBox_2)
        self.hexa_button.setObjectName(_fromUtf8("hexa_button"))
        self.gridLayout_3.addWidget(self.hexa_button, 14, 0, 1, 3)
        self.tilt_entry = QtGui.QLineEdit(self.groupBox_2)
        self.tilt_entry.setObjectName(_fromUtf8("tilt_entry"))
        self.gridLayout_3.addWidget(self.tilt_entry, 4, 3, 1, 1)
        self.tilt_label = QtGui.QLabel(self.groupBox_2)
        self.tilt_label.setObjectName(_fromUtf8("tilt_label"))
        self.gridLayout_3.addWidget(self.tilt_label, 4, 0, 1, 1)
        self.diff1_entry = QtGui.QLineEdit(self.groupBox_2)
        self.diff1_entry.setObjectName(_fromUtf8("diff1_entry"))
        self.gridLayout_3.addWidget(self.diff1_entry, 3, 0, 1, 1)
        self.inclination_label = QtGui.QLabel(self.groupBox_2)
        self.inclination_label.setObjectName(_fromUtf8("inclination_label"))
        self.gridLayout_3.addWidget(self.inclination_label, 10, 0, 1, 3)
        self.inclinaison_entry = QtGui.QLineEdit(self.groupBox_2)
        self.inclinaison_entry.setObjectName(_fromUtf8("inclinaison_entry"))
        self.gridLayout_3.addWidget(self.inclinaison_entry, 10, 3, 1, 1)
        self.rg_label = QtGui.QLabel(self.groupBox_2)
        self.rg_label.setText(_fromUtf8(""))
        self.rg_label.setObjectName(_fromUtf8("rg_label"))
        self.gridLayout_3.addWidget(self.rg_label, 18, 2, 1, 1)
        self.rot_diff_label = QtGui.QLabel(self.groupBox_2)
        self.rot_diff_label.setObjectName(_fromUtf8("rot_diff_label"))
        self.gridLayout_3.addWidget(self.rot_diff_label, 16, 0, 1, 4)
        self.rot_gm_button = QtGui.QPushButton(self.groupBox_2)
        self.rot_gm_button.setObjectName(_fromUtf8("rot_gm_button"))
        self.gridLayout_3.addWidget(self.rot_gm_button, 17, 0, 1, 1)
        self.rot_g_entry = QtGui.QLineEdit(self.groupBox_2)
        self.rot_g_entry.setObjectName(_fromUtf8("rot_g_entry"))
        self.gridLayout_3.addWidget(self.rot_g_entry, 17, 2, 1, 1)
        self.button_trace = QtGui.QPushButton(self.groupBox_2)
        self.button_trace.setObjectName(_fromUtf8("button_trace"))
        self.gridLayout_3.addWidget(self.button_trace, 11, 0, 1, 3)
        self.diff2_entry = QtGui.QLineEdit(self.groupBox_2)
        self.diff2_entry.setObjectName(_fromUtf8("diff2_entry"))
        self.gridLayout_3.addWidget(self.diff2_entry, 3, 2, 1, 1)
        self.rot_gp_button = QtGui.QPushButton(self.groupBox_2)
        self.rot_gp_button.setObjectName(_fromUtf8("rot_gp_button"))
        self.gridLayout_3.addWidget(self.rot_gp_button, 17, 3, 1, 1)
        self.diff3_entry = QtGui.QLineEdit(self.groupBox_2)
        self.diff3_entry.setObjectName(_fromUtf8("diff3_entry"))
        self.gridLayout_3.addWidget(self.diff3_entry, 3, 3, 1, 1)
        self.uvw_button = QtGui.QCheckBox(self.groupBox_2)
        self.uvw_button.setObjectName(_fromUtf8("uvw_button"))
        self.gridLayout_3.addWidget(self.uvw_button, 12, 0, 1, 3)
        self.gridLayout.addWidget(self.groupBox_2, 2, 1, 1, 1)
        self.groupBox = QtGui.QGroupBox(self.centralwidget)
        self.groupBox.setMaximumSize(QtCore.QSize(160, 16777215))
        self.groupBox.setObjectName(_fromUtf8("groupBox"))
        self.gridLayout_2 = QtGui.QGridLayout(self.groupBox)
        self.gridLayout_2.setMargin(5)
        self.gridLayout_2.setSpacing(5)
        self.gridLayout_2.setObjectName(_fromUtf8("gridLayout_2"))
        self.space_group_Box = QtGui.QComboBox(self.groupBox)
        self.space_group_Box.setObjectName(_fromUtf8("space_group_Box"))
        self.gridLayout_2.addWidget(self.space_group_Box, 7, 0, 1, 6)
        self.dm_button = QtGui.QPushButton(self.groupBox)
        self.dm_button.setObjectName(_fromUtf8("dm_button"))
        self.gridLayout_2.addWidget(self.dm_button, 9, 1, 1, 1)
        self.b_label = QtGui.QLabel(self.groupBox)
        self.b_label.setObjectName(_fromUtf8("b_label"))
        self.gridLayout_2.addWidget(self.b_label, 1, 0, 1, 1)
        self.d_label = QtGui.QLabel(self.groupBox)
        self.d_label.setObjectName(_fromUtf8("d_label"))
        self.gridLayout_2.addWidget(self.d_label, 9, 0, 1, 1)
        self.a_label = QtGui.QLabel(self.groupBox)
        self.a_label.setObjectName(_fromUtf8("a_label"))
        self.gridLayout_2.addWidget(self.a_label, 0, 0, 1, 1)
        self.d_entry = QtGui.QLineEdit(self.groupBox)
        self.d_entry.setObjectName(_fromUtf8("d_entry"))
        self.gridLayout_2.addWidget(self.d_entry, 9, 2, 1, 1)
        self.dp_button = QtGui.QPushButton(self.groupBox)
        self.dp_button.setObjectName(_fromUtf8("dp_button"))
        self.gridLayout_2.addWidget(self.dp_button, 9, 4, 1, 1)
        self.c_label = QtGui.QLabel(self.groupBox)
        self.c_label.setObjectName(_fromUtf8("c_label"))
        self.gridLayout_2.addWidget(self.c_label, 2, 0, 1, 1)
        self.d_label_var = QtGui.QLabel(self.groupBox)
        self.d_label_var.setText(_fromUtf8(""))
        self.d_label_var.setObjectName(_fromUtf8("d_label_var"))
        self.gridLayout_2.addWidget(self.d_label_var, 9, 5, 1, 1)
        self.gamma_entry = QtGui.QLineEdit(self.groupBox)
        self.gamma_entry.setObjectName(_fromUtf8("gamma_entry"))
        self.gridLayout_2.addWidget(self.gamma_entry, 2, 5, 1, 1)
        self.alpha_entry = QtGui.QLineEdit(self.groupBox)
        self.alpha_entry.setObjectName(_fromUtf8("alpha_entry"))
        self.gridLayout_2.addWidget(self.alpha_entry, 0, 5, 1, 1)
        self.beta_entry = QtGui.QLineEdit(self.groupBox)
        self.beta_entry.setObjectName(_fromUtf8("beta_entry"))
        self.gridLayout_2.addWidget(self.beta_entry, 1, 5, 1, 1)
        self.e_entry = QtGui.QLineEdit(self.groupBox)
        self.e_entry.setObjectName(_fromUtf8("e_entry"))
        self.gridLayout_2.addWidget(self.e_entry, 6, 5, 1, 1)
        self.e_label = QtGui.QLabel(self.groupBox)
        self.e_label.setObjectName(_fromUtf8("e_label"))
        self.gridLayout_2.addWidget(self.e_label, 6, 0, 1, 5)
        self.alpha_label = QtGui.QLabel(self.groupBox)
        self.alpha_label.setObjectName(_fromUtf8("alpha_label"))
        self.gridLayout_2.addWidget(self.alpha_label, 0, 3, 1, 2)
        self.a_entry = QtGui.QLineEdit(self.groupBox)
        self.a_entry.setObjectName(_fromUtf8("a_entry"))
        self.gridLayout_2.addWidget(self.a_entry, 0, 1, 1, 2)
        self.b_entry = QtGui.QLineEdit(self.groupBox)
        self.b_entry.setObjectName(_fromUtf8("b_entry"))
        self.gridLayout_2.addWidget(self.b_entry, 1, 1, 1, 2)
        self.gamma_label = QtGui.QLabel(self.groupBox)
        self.gamma_label.setObjectName(_fromUtf8("gamma_label"))
        self.gridLayout_2.addWidget(self.gamma_label, 2, 3, 1, 2)
        self.c_entry = QtGui.QLineEdit(self.groupBox)
        self.c_entry.setObjectName(_fromUtf8("c_entry"))
        self.gridLayout_2.addWidget(self.c_entry, 2, 1, 1, 2)
        self.reciprocal_checkBox = QtGui.QCheckBox(self.groupBox)
        self.reciprocal_checkBox.setObjectName(_fromUtf8("reciprocal_checkBox"))
        self.gridLayout_2.addWidget(self.reciprocal_checkBox, 8, 0, 1, 6)
        self.beta_label = QtGui.QLabel(self.groupBox)
        self.beta_label.setObjectName(_fromUtf8("beta_label"))
        self.gridLayout_2.addWidget(self.beta_label, 1, 3, 1, 2)
        self.gridLayout.addWidget(self.groupBox, 1, 1, 1, 1)
        self.groupBox_9 = QtGui.QGroupBox(self.centralwidget)
        self.groupBox_9.setMaximumSize(QtCore.QSize(170, 16777215))
        self.groupBox_9.setObjectName(_fromUtf8("groupBox_9"))
        self.gridLayout_10 = QtGui.QGridLayout(self.groupBox_9)
        self.gridLayout_10.setObjectName(_fromUtf8("gridLayout_10"))
        self.size_var = QtGui.QLineEdit(self.groupBox_9)
        self.size_var.setObjectName(_fromUtf8("size_var"))
        self.gridLayout_10.addWidget(self.size_var, 5, 2, 1, 1)
        self.color_trace_rouge = QtGui.QRadioButton(self.groupBox_9)
        self.color_trace_rouge.setObjectName(_fromUtf8("color_trace_rouge"))
        self.gridLayout_10.addWidget(self.color_trace_rouge, 2, 0, 1, 1)
        self.size_var_label = QtGui.QLabel(self.groupBox_9)
        self.size_var_label.setObjectName(_fromUtf8("size_var_label"))
        self.gridLayout_10.addWidget(self.size_var_label, 5, 0, 1, 2)
        self.color_trace_vert = QtGui.QRadioButton(self.groupBox_9)
        self.color_trace_vert.setObjectName(_fromUtf8("color_trace_vert"))
        self.gridLayout_10.addWidget(self.color_trace_vert, 0, 1, 1, 2)
        self.style_box = QtGui.QCheckBox(self.groupBox_9)
        self.style_box.setObjectName(_fromUtf8("style_box"))
        self.gridLayout_10.addWidget(self.style_box, 3, 0, 1, 3)
        self.reset_view_button = QtGui.QPushButton(self.groupBox_9)
        self.reset_view_button.setObjectName(_fromUtf8("reset_view_button"))
        self.gridLayout_10.addWidget(self.reset_view_button, 6, 0, 1, 3)
        self.color_trace_bleu = QtGui.QRadioButton(self.groupBox_9)
        self.color_trace_bleu.setObjectName(_fromUtf8("color_trace_bleu"))
        self.gridLayout_10.addWidget(self.color_trace_bleu, 0, 0, 1, 1)
        self.wulff_button = QtGui.QCheckBox(self.groupBox_9)
        self.wulff_button.setObjectName(_fromUtf8("wulff_button"))
        self.gridLayout_10.addWidget(self.wulff_button, 4, 0, 1, 3)
        self.gridLayout.addWidget(self.groupBox_9, 3, 1, 1, 1)
        self.groupBox_3 = QtGui.QGroupBox(self.centralwidget)
        self.groupBox_3.setMaximumSize(QtCore.QSize(150, 16777215))
        self.groupBox_3.setObjectName(_fromUtf8("groupBox_3"))
        self.gridLayout_4 = QtGui.QGridLayout(self.groupBox_3)
        self.gridLayout_4.setMargin(5)
        self.gridLayout_4.setSpacing(5)
        self.gridLayout_4.setObjectName(_fromUtf8("gridLayout_4"))
        self.angle_beta_entry = QtGui.QLineEdit(self.groupBox_3)
        self.angle_beta_entry.setObjectName(_fromUtf8("angle_beta_entry"))
        self.gridLayout_4.addWidget(self.angle_beta_entry, 8, 2, 1, 1)
        self.angle_beta_buttonp = QtGui.QPushButton(self.groupBox_3)
        self.angle_beta_buttonp.setObjectName(_fromUtf8("angle_beta_buttonp"))
        self.gridLayout_4.addWidget(self.angle_beta_buttonp, 8, 3, 1, 1)
        self.angle_z_buttonm = QtGui.QPushButton(self.groupBox_3)
        self.angle_z_buttonm.setObjectName(_fromUtf8("angle_z_buttonm"))
        self.gridLayout_4.addWidget(self.angle_z_buttonm, 12, 1, 1, 1)
        self.angle_alpha_buttonp = QtGui.QPushButton(self.groupBox_3)
        self.angle_alpha_buttonp.setObjectName(_fromUtf8("angle_alpha_buttonp"))
        self.gridLayout_4.addWidget(self.angle_alpha_buttonp, 4, 3, 1, 1)
        self.angle_alpha_buttonm = QtGui.QPushButton(self.groupBox_3)
        self.angle_alpha_buttonm.setObjectName(_fromUtf8("angle_alpha_buttonm"))
        self.gridLayout_4.addWidget(self.angle_alpha_buttonm, 4, 1, 1, 1)
        self.angle_alpha_entry = QtGui.QLineEdit(self.groupBox_3)
        self.angle_alpha_entry.setObjectName(_fromUtf8("angle_alpha_entry"))
        self.gridLayout_4.addWidget(self.angle_alpha_entry, 4, 2, 1, 1)
        self.angle_z_entry = QtGui.QLineEdit(self.groupBox_3)
        self.angle_z_entry.setObjectName(_fromUtf8("angle_z_entry"))
        self.gridLayout_4.addWidget(self.angle_z_entry, 12, 2, 1, 1)
        self.angle_beta_buttonm = QtGui.QPushButton(self.groupBox_3)
        self.angle_beta_buttonm.setObjectName(_fromUtf8("angle_beta_buttonm"))
        self.gridLayout_4.addWidget(self.angle_beta_buttonm, 8, 1, 1, 1)
        self.angle_z_buttonp = QtGui.QPushButton(self.groupBox_3)
        self.angle_z_buttonp.setObjectName(_fromUtf8("angle_z_buttonp"))
        self.gridLayout_4.addWidget(self.angle_z_buttonp, 12, 3, 1, 1)
        self.angle_z_label = QtGui.QLabel(self.groupBox_3)
        self.angle_z_label.setObjectName(_fromUtf8("angle_z_label"))
        self.gridLayout_4.addWidget(self.angle_z_label, 9, 0, 1, 3)
        self.angle_beta_label = QtGui.QLabel(self.groupBox_3)
        self.angle_beta_label.setObjectName(_fromUtf8("angle_beta_label"))
        self.gridLayout_4.addWidget(self.angle_beta_label, 6, 0, 1, 2)
        self.angle_beta_label_2 = QtGui.QLabel(self.groupBox_3)
        self.angle_beta_label_2.setText(_fromUtf8(""))
        self.angle_beta_label_2.setObjectName(_fromUtf8("angle_beta_label_2"))
        self.gridLayout_4.addWidget(self.angle_beta_label_2, 6, 3, 1, 1)
        self.angle_alpha_label_2 = QtGui.QLabel(self.groupBox_3)
        self.angle_alpha_label_2.setText(_fromUtf8(""))
        self.angle_alpha_label_2.setObjectName(_fromUtf8("angle_alpha_label_2"))
        self.gridLayout_4.addWidget(self.angle_alpha_label_2, 1, 3, 1, 1)
        self.angle_alpha_label = QtGui.QLabel(self.groupBox_3)
        self.angle_alpha_label.setObjectName(_fromUtf8("angle_alpha_label"))
        self.gridLayout_4.addWidget(self.angle_alpha_label, 1, 0, 1, 3)
        self.angle_z_label_2 = QtGui.QLabel(self.groupBox_3)
        self.angle_z_label_2.setText(_fromUtf8(""))
        self.angle_z_label_2.setObjectName(_fromUtf8("angle_z_label_2"))
        self.gridLayout_4.addWidget(self.angle_z_label_2, 9, 3, 1, 1)
        self.lock_checkButton = QtGui.QCheckBox(self.groupBox_3)
        self.lock_checkButton.setObjectName(_fromUtf8("lock_checkButton"))
        self.gridLayout_4.addWidget(self.lock_checkButton, 0, 0, 1, 4)
        self.gridLayout.addWidget(self.groupBox_3, 1, 3, 1, 1)
        self.gridLayout_7.addLayout(self.gridLayout, 1, 1, 1, 1)
        self.mplwindow = QtGui.QWidget(self.centralwidget)
        self.mplwindow.setMinimumSize(QtCore.QSize(800, 800))
        self.mplwindow.setMaximumSize(QtCore.QSize(800, 800))
        self.mplwindow.setObjectName(_fromUtf8("mplwindow"))
        self.gridLayoutWidget = QtGui.QWidget(self.mplwindow)
        self.gridLayoutWidget.setGeometry(QtCore.QRect(0, 0, 801, 801))
        self.gridLayoutWidget.setObjectName(_fromUtf8("gridLayoutWidget"))
        self.mplvl = QtGui.QGridLayout(self.gridLayoutWidget)
        self.mplvl.setMargin(0)
        self.mplvl.setObjectName(_fromUtf8("mplvl"))
        self.gridLayout_7.addWidget(self.mplwindow, 1, 0, 1, 1)
        StereoProj.setCentralWidget(self.centralwidget)
        self.menubar = QtGui.QMenuBar(StereoProj)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1152, 23))
        self.menubar.setObjectName(_fromUtf8("menubar"))
        self.menuSave = QtGui.QMenu(self.menubar)
        self.menuSave.setObjectName(_fromUtf8("menuSave"))
        self.menuStructure = QtGui.QMenu(self.menubar)
        self.menuStructure.setObjectName(_fromUtf8("menuStructure"))
        self.menuAngle = QtGui.QMenu(self.menubar)
        self.menuAngle.setObjectName(_fromUtf8("menuAngle"))
        self.menuSchmid_factor = QtGui.QMenu(self.menubar)
        self.menuSchmid_factor.setObjectName(_fromUtf8("menuSchmid_factor"))
        self.menuXyz_directions = QtGui.QMenu(self.menubar)
        self.menuXyz_directions.setObjectName(_fromUtf8("menuXyz_directions"))
        self.menuWidth = QtGui.QMenu(self.menubar)
        self.menuWidth.setObjectName(_fromUtf8("menuWidth"))
        self.menuIntersections = QtGui.QMenu(self.menubar)
        self.menuIntersections.setObjectName(_fromUtf8("menuIntersections"))
        self.menuDiffraction = QtGui.QMenu(self.menubar)
        self.menuDiffraction.setObjectName(_fromUtf8("menuDiffraction"))
        StereoProj.setMenuBar(self.menubar)
        self.statusbar = QtGui.QStatusBar(StereoProj)
        self.statusbar.setObjectName(_fromUtf8("statusbar"))
        StereoProj.setStatusBar(self.statusbar)
        self.actionSave_figure = QtGui.QAction(StereoProj)
        self.actionSave_figure.setObjectName(_fromUtf8("actionSave_figure"))
        self.actionCalculate_Schmid_factor = QtGui.QAction(StereoProj)
        self.actionCalculate_Schmid_factor.setObjectName(_fromUtf8("actionCalculate_Schmid_factor"))
        self.actionCalculate_angle = QtGui.QAction(StereoProj)
        self.actionCalculate_angle.setObjectName(_fromUtf8("actionCalculate_angle"))
        self.actionCalculate_xyz = QtGui.QAction(StereoProj)
        self.actionCalculate_xyz.setObjectName(_fromUtf8("actionCalculate_xyz"))
        self.actionCalculate_apparent_width = QtGui.QAction(StereoProj)
        self.actionCalculate_apparent_width.setObjectName(_fromUtf8("actionCalculate_apparent_width"))
        self.actionPlanes = QtGui.QAction(StereoProj)
        self.actionPlanes.setObjectName(_fromUtf8("actionPlanes"))
        self.actionProj_directions = QtGui.QAction(StereoProj)
        self.actionProj_directions.setObjectName(_fromUtf8("actionProj_directions"))
        self.actionPlane_cone = QtGui.QAction(StereoProj)
        self.actionPlane_cone.setObjectName(_fromUtf8("actionPlane_cone"))
        self.actionCalculate_intersections = QtGui.QAction(StereoProj)
        self.actionCalculate_intersections.setObjectName(_fromUtf8("actionCalculate_intersections"))
        self.actionHkl_uvw = QtGui.QAction(StereoProj)
        self.actionHkl_uvw.setObjectName(_fromUtf8("actionHkl_uvw"))
        self.actionPlot_Kikuchi_lines = QtGui.QAction(StereoProj)
        self.actionPlot_Kikuchi_lines.setObjectName(_fromUtf8("actionPlot_Kikuchi_lines"))
        self.menuSave.addAction(self.actionSave_figure)
        self.menuAngle.addAction(self.actionCalculate_angle)
        self.menuSchmid_factor.addAction(self.actionCalculate_Schmid_factor)
        self.menuXyz_directions.addAction(self.actionCalculate_xyz)
        self.menuXyz_directions.addAction(self.actionHkl_uvw)
        self.menuWidth.addAction(self.actionCalculate_apparent_width)
        self.menuIntersections.addAction(self.actionCalculate_intersections)
        self.menuDiffraction.addAction(self.actionPlot_Kikuchi_lines)
        self.menubar.addAction(self.menuSave.menuAction())
        self.menubar.addAction(self.menuStructure.menuAction())
        self.menubar.addAction(self.menuAngle.menuAction())
        self.menubar.addAction(self.menuSchmid_factor.menuAction())
        self.menubar.addAction(self.menuXyz_directions.menuAction())
        self.menubar.addAction(self.menuWidth.menuAction())
        self.menubar.addAction(self.menuIntersections.menuAction())
        self.menubar.addAction(self.menuDiffraction.menuAction())

        self.retranslateUi(StereoProj)
        QtCore.QMetaObject.connectSlotsByName(StereoProj)
        StereoProj.setTabOrder(self.a_entry, self.b_entry)
        StereoProj.setTabOrder(self.b_entry, self.c_entry)
        StereoProj.setTabOrder(self.c_entry, self.alpha_entry)
        StereoProj.setTabOrder(self.alpha_entry, self.beta_entry)
        StereoProj.setTabOrder(self.beta_entry, self.gamma_entry)
        StereoProj.setTabOrder(self.gamma_entry, self.e_entry)
        StereoProj.setTabOrder(self.e_entry, self.angle_alpha_buttonm)
        StereoProj.setTabOrder(self.angle_alpha_buttonm, self.angle_alpha_entry)
        StereoProj.setTabOrder(self.angle_alpha_entry, self.angle_alpha_buttonp)
        StereoProj.setTabOrder(self.angle_alpha_buttonp, self.angle_beta_buttonm)
        StereoProj.setTabOrder(self.angle_beta_buttonm, self.angle_beta_entry)
        StereoProj.setTabOrder(self.angle_beta_entry, self.angle_beta_buttonp)
        StereoProj.setTabOrder(self.angle_beta_buttonp, self.angle_z_buttonm)
        StereoProj.setTabOrder(self.angle_z_buttonm, self.angle_z_entry)
        StereoProj.setTabOrder(self.angle_z_entry, self.angle_z_buttonp)
        StereoProj.setTabOrder(self.angle_z_buttonp, self.d_entry)
        StereoProj.setTabOrder(self.d_entry, self.dm_button)
        StereoProj.setTabOrder(self.dm_button, self.dp_button)
        StereoProj.setTabOrder(self.dp_button, self.diff1_entry)
        StereoProj.setTabOrder(self.diff1_entry, self.diff2_entry)
        StereoProj.setTabOrder(self.diff2_entry, self.diff3_entry)
        StereoProj.setTabOrder(self.diff3_entry, self.tilt_entry)
        StereoProj.setTabOrder(self.tilt_entry, self.inclinaison_entry)
        StereoProj.setTabOrder(self.inclinaison_entry, self.button_trace)
        StereoProj.setTabOrder(self.button_trace, self.uvw_button)
        StereoProj.setTabOrder(self.uvw_button, self.hexa_button)
        StereoProj.setTabOrder(self.hexa_button, self.rot_gm_button)
        StereoProj.setTabOrder(self.rot_gm_button, self.rot_g_entry)
        StereoProj.setTabOrder(self.rot_g_entry, self.rot_gp_button)
        StereoProj.setTabOrder(self.rot_gp_button, self.pole1_entry)
        StereoProj.setTabOrder(self.pole1_entry, self.pole2_entry)
        StereoProj.setTabOrder(self.pole2_entry, self.pole3_entry)
        StereoProj.setTabOrder(self.pole3_entry, self.addpole_button)
        StereoProj.setTabOrder(self.addpole_button, self.undo_addpole_button)
        StereoProj.setTabOrder(self.undo_addpole_button, self.sym_button)
        StereoProj.setTabOrder(self.sym_button, self.undo_sym_button)
        StereoProj.setTabOrder(self.undo_sym_button, self.trace_plan_button)
        StereoProj.setTabOrder(self.trace_plan_button, self.undo_trace_plan_button)
        StereoProj.setTabOrder(self.undo_trace_plan_button, self.trace_plan_sym_button)
        StereoProj.setTabOrder(self.trace_plan_sym_button, self.undo_trace_plan_sym_button)
        StereoProj.setTabOrder(self.undo_trace_plan_sym_button, self.trace_schmid_button)
        StereoProj.setTabOrder(self.trace_schmid_button, self.undo_trace_schmid)
        StereoProj.setTabOrder(self.undo_trace_schmid, self.norm_button)
        StereoProj.setTabOrder(self.norm_button, self.phi1_entry)
        StereoProj.setTabOrder(self.phi1_entry, self.phi_entry)
        StereoProj.setTabOrder(self.phi_entry, self.phi2_entry)
        StereoProj.setTabOrder(self.phi2_entry, self.button_trace2)
        StereoProj.setTabOrder(self.button_trace2, self.color_trace_bleu)
        StereoProj.setTabOrder(self.color_trace_bleu, self.color_trace_vert)
        StereoProj.setTabOrder(self.color_trace_vert, self.color_trace_rouge)
        StereoProj.setTabOrder(self.color_trace_rouge, self.style_box)
        StereoProj.setTabOrder(self.style_box, self.size_var)

    def retranslateUi(self, StereoProj):
        StereoProj.setWindowTitle(_translate("StereoProj", "Stereo-Proj", None))
        self.groupBox_5.setTitle(_translate("StereoProj", "Euler Angles", None))
        self.lab_coord.setText(_translate("StereoProj", "Tilt, Inclination", None))
        self.button_trace2.setText(_translate("StereoProj", "PLOT", None))
        self.lab_euler2.setText(_translate("StereoProj", "Phi 1, Phi, Phi2", None))
        self.pushButton_copy_to_euler.setText(_translate("StereoProj", "Copy to Euler", None))
        self.groupBox_4.setTitle(_translate("StereoProj", "Pole/Plane", None))
        self.undo_trace_schmid.setText(_translate("StereoProj", "-", None))
        self.norm_button.setText(_translate("StereoProj", "dhkl", None))
        self.undo_sym_button.setText(_translate("StereoProj", "-", None))
        self.trace_schmid_button.setText(_translate("StereoProj", "Schmid", None))
        self.addpole_button.setText(_translate("StereoProj", "Add", None))
        self.trace_plan_button.setText(_translate("StereoProj", " Plane", None))
        self.undo_trace_plan_sym_button.setText(_translate("StereoProj", "-", None))
        self.trace_plan_sym_button.setText(_translate("StereoProj", "Sym Plane", None))
        self.sym_button.setText(_translate("StereoProj", "Symmetry", None))
        self.undo_trace_plan_button.setText(_translate("StereoProj", "-", None))
        self.undo_addpole_button.setText(_translate("StereoProj", "-", None))
        self.undo_trace_cone_button.setText(_translate("StereoProj", "-", None))
        self.trace_cone_button.setText(_translate("StereoProj", "Cone", None))
        self.groupBox_2.setTitle(_translate("StereoProj", "Axis/Rotation", None))
        self.diff_label.setText(_translate("StereoProj", "g-vector", None))
        self.hexa_button.setText(_translate("StereoProj", "hexa", None))
        self.tilt_label.setText(_translate("StereoProj", "Tilt", None))
        self.inclination_label.setText(_translate("StereoProj", "Inclination", None))
        self.rot_diff_label.setText(_translate("StereoProj", "Rotation along g", None))
        self.rot_gm_button.setText(_translate("StereoProj", "-", None))
        self.button_trace.setText(_translate("StereoProj", "PLOT", None))
        self.rot_gp_button.setText(_translate("StereoProj", "+", None))
        self.uvw_button.setText(_translate("StereoProj", "uvw", None))
        self.groupBox.setTitle(_translate("StereoProj", "Crystal Parameters", None))
        self.dm_button.setText(_translate("StereoProj", "-", None))
        self.b_label.setText(_translate("StereoProj", "b", None))
        self.d_label.setText(_translate("StereoProj", "d", None))
        self.a_label.setText(_translate("StereoProj", "a", None))
        self.dp_button.setText(_translate("StereoProj", "+", None))
        self.c_label.setText(_translate("StereoProj", "c", None))
        self.e_label.setText(_translate("StereoProj", "max indices", None))
        self.alpha_label.setText(_translate("StereoProj", "<p>&alpha;</p>", None))
        self.gamma_label.setText(_translate("StereoProj", "<p>&gamma;</p>", None))
        self.reciprocal_checkBox.setText(_translate("StereoProj", "Reciprocal indices", None))
        self.beta_label.setText(_translate("StereoProj", "<p>&beta;</p>", None))
        self.groupBox_9.setTitle(_translate("StereoProj", "Layout", None))
        self.color_trace_rouge.setText(_translate("StereoProj", "red", None))
        self.size_var_label.setText(_translate("StereoProj", "Marker size", None))
        self.color_trace_vert.setText(_translate("StereoProj", "green", None))
        self.style_box.setText(_translate("StereoProj", "open/filled", None))
        self.reset_view_button.setText(_translate("StereoProj", "reset view", None))
        self.color_trace_bleu.setText(_translate("StereoProj", "blue", None))
        self.wulff_button.setText(_translate("StereoProj", "Wulff net", None))
        self.groupBox_3.setTitle(_translate("StereoProj", "Rotation", None))
        self.angle_beta_buttonp.setText(_translate("StereoProj", "+", None))
        self.angle_z_buttonm.setText(_translate("StereoProj", "-", None))
        self.angle_alpha_buttonp.setText(_translate("StereoProj", "+", None))
        self.angle_alpha_buttonm.setText(_translate("StereoProj", "-", None))
        self.angle_beta_buttonm.setText(_translate("StereoProj", "-", None))
        self.angle_z_buttonp.setText(_translate("StereoProj", "+", None))
        self.angle_z_label.setText(_translate("StereoProj", "theta/z", None))
        self.angle_beta_label.setText(_translate("StereoProj", "beta/x", None))
        self.angle_alpha_label.setText(_translate("StereoProj", "alpha/y", None))
        self.lock_checkButton.setText(_translate("StereoProj", "Lock Axes", None))
        self.menuSave.setTitle(_translate("StereoProj", "Save", None))
        self.menuStructure.setTitle(_translate("StereoProj", "Structure", None))
        self.menuAngle.setTitle(_translate("StereoProj", "Angle", None))
        self.menuSchmid_factor.setTitle(_translate("StereoProj", "Schmid factor", None))
        self.menuXyz_directions.setTitle(_translate("StereoProj", "xyz directions", None))
        self.menuWidth.setTitle(_translate("StereoProj", "Width", None))
        self.menuIntersections.setTitle(_translate("StereoProj", "intersections", None))
        self.menuDiffraction.setTitle(_translate("StereoProj", "Diffraction", None))
        self.actionSave_figure.setText(_translate("StereoProj", "Save figure", None))
        self.actionCalculate_Schmid_factor.setText(_translate("StereoProj", "calculate Schmid factor", None))
        self.actionCalculate_angle.setText(_translate("StereoProj", "Calculate angle", None))
        self.actionCalculate_xyz.setText(_translate("StereoProj", "calculate xyz directions", None))
        self.actionCalculate_apparent_width.setText(_translate("StereoProj", "Calculate apparent width", None))
        self.actionPlanes.setText(_translate("StereoProj", "planes", None))
        self.actionProj_directions.setText(_translate("StereoProj", "proj. directions", None))
        self.actionPlane_cone.setText(_translate("StereoProj", "plane-cone", None))
        self.actionCalculate_intersections.setText(_translate("StereoProj", "Calculate intersections", None))
        self.actionHkl_uvw.setText(_translate("StereoProj", "hkl <> uvw", None))
        self.actionPlot_Kikuchi_lines.setText(_translate("StereoProj", "plot Kikuchi lines", None))

